### ISSUE TITLE
Compile for ARM-based Linux? 

### ISSUE THREAD

**Issue by pianoman723** [sillsdev/chorus#130]
Hello there, wondering if chorus hub could be recompiled for Linux running on an ARM chip? I'm looking at outfitting a new remote translation house with a Raspberry pi 3 just to be a low power server for chorus hub and some file sharing. I was bummed to find I couldn't run chorus on an ARM processor. Not sure what all your dependencies look like, but thought I'd ask the question and see if someone would be willing to compile the package for ARM. Thanks.

**Comment by ermshiperete** [comment]
Unfortunately we only have limited resources available, so ARM is not in the list of supported architectures. And we're not set up to build and provide packages for ARM. Sorry.

**Comment by papeh** [comment]
I received another request for this from a field worker this week. Unfortunately, we'd need significant demand to make this worth considering.
